apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: default
data:
  nats.conf: |
    server_name: $POD_NAME
    jetstream {
      store_dir: /data/jetstream
      max_mem: 1G
      max_file: 10G
    }
    cluster {
      port: 6222
      name: todo-cluster
      routes: [
        "nats://nats-0.nats.default.svc:6222",
        "nats://nats-1.nats.default.svc:6222",
        "nats://nats-2.nats.default.svc:6222"
      ]
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: default
spec:
  selector:
    matchLabels:
      app: nats
  serviceName: nats
  replicas: 3
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 6222
              name: cluster
            - containerPort: 8222
              name: monitor
          volumeMounts:
            - name: config
              mountPath: /etc/nats-config
            - name: data
              mountPath: /data/jetstream
          command: ["nats-server"]
          args: ["-c", "/etc/nats-config/nats.conf"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: config
          configMap:
            name: nats-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: default
spec:
  ports:
    - port: 4222
      name: client
    - port: 6222
      name: cluster
    - port: 8222
      name: monitor
  clusterIP: None
  selector:
    app: nats
